### ISSUE TITLE
Listen Address

### ISSUE THREAD

**Issue by hobbyquaker** [holgerimbery/docker_hm2mqtt#1]
Hallo Holger,

finde ich cool dass Du ein Docker Container dafür baust!

Ich fürchte allerdings Du wirst beim "Dockerisieren" von hm2mqtt.js auf ein Problem stoßen. hm2mqtt teilt der CCU mit unter welcher Adresse es erreichbar ist, die gleiche Adresse wird allerdings auch benutzt um die Server die die CCU dann ansprechen will zu binden. D.h. hm2mqtt wird hier nur das container-interne Netz nutzen können, das kann aber von der CCU nicht erreicht werden - dann kommen keine Events an.
Ich werde das auftrennen auf 2 config optionen für das Binding des Servers und die Mitteilung der Adresse an die CCU im rpc init. Gib mir ein paar Tage, ich geb Bescheid sobald das erledigt ist.

Viele Grüße,
Sebastian

**Comment by holgerimbery** [comment]
Hallo Sebastian,
darauf bin ich schon gestossen - als container geht es gerade noch (--net host).
Ich war allerdings so naiv und habs auch als Service im swarm probiert und da ist es mir, natürlich, um die Ohren geflogen.
Danke für Dein Angebot!!

Gruß,
Holger

**Comment by hobbyquaker** [comment]
So, bin soweit, v1.0.8 ist released :) Hab ein neuen command line param `--init-address` eingeführt, dort kann man die Adresse angeben die beim RPC init der CCU mitgeteilt wird, also die Adresse unter der die CCU dann events bei hm2mqtt abliefern will.

**Comment by holgerimbery** [comment]
Danke Dir !!! Ich baue es ein und teste es im swarm. Das Image baue ich für amd64 und arm

**Comment by holgerimbery** [comment]
closed - --init-address solved the issue
