### ISSUE TITLE
Use new base image

### ISSUE THREAD

**Issue by dersimn** [holgerimbery/docker_hm2mqtt#1]
See depreciation notice for your `Dockerfile.armhf` base image: https://hub.docker.com/r/hypriot/rpi-node

**Comment by holgerimbery** [comment]
hypriot is depreciated and the official images are still experimental

`
THESE IMAGES ARE VERY EXPERIMENTAL; THEY ARE PROVIDED ON A BEST-EFFORT BASIS WHILE docker-library/official-images#2289 IS STILL IN-PROGRESS (which is the first step towards proper multiarch images)
` 
Let´s wait and see ...

**Comment by holgerimbery** [comment]
@dersimn adventurous today :-) ? give holgerimbery/docker_hm2mqtt:armhf-v2.2.4-develop a chance (based on official node:slim)

**Comment by holgerimbery** [comment]
moved to own multiarch base image
